name: lxp-bridge (dev version)
version: dev
slug: lxp-bridge-dev
description: Allows local communication with Luxpower inverters and bridges it to MQTT
arch:
- armv7
- aarch64
- amd64
url: "https://github.com/celsworth/lxp-bridge"
init: false
startup: application
stage: experimental
options:
  loglevel: info
  inverters:
  - enabled: true
    host: ""
    port: 8000
    serial: ""
    datalog: ""
    heartbeats: false
    publish_holdings_on_connect: false
  databases:
  - enabled: false
    url: "postgres://lxp:lxp@localhost/lxp"
  mqtt:
    enabled: true
    host: "localhost"
    port: 1883
    username: ""
    password: ""
    namespace: lxp
  influx:
    enabled: false
    url: "http://localhost:8086"
    username: ""
    password: ""
    database: "lxp"
  scheduler:
    enabled: yes
    timesync_cron: "0 0 * * *"
schema:
  loglevel: list(trace|debug|info|warn|error|off)
  inverters:
  - enabled: bool
    host: str
    port: port
    serial: str
    datalog: str
    heartbeats: bool
    publish_holdings_on_connect: bool
  databases:
  - enabled: bool
    url: url
  mqtt:
    enabled: bool
    host: str
    port: port
    username: str
    password: password
    namespace: str
  influx:
    enabled: bool
    url: url
    username: str
    password: password
    database: str
  scheduler:
    enabled: bool
    timesync_cron: str
