name: lxp-bridge
version: v0.10.0
slug: lxp-bridge
description: lxp-bridge is a tool to communicate with a LuxPower inverter (commonly used with home-battery and solar setups), written in Rust.  It allows you to monitor and control your inverter locally without any dependence on the manufacturer's own servers in China.
arch: [armhf, armv7, aarch64, amd64, i386]
url: "https://github.com/celsworth/lxp-bridge"
startup: application
stage: experimental
options:
  inverters:
  - enabled: true
    host: ""
    port: 8000
    serial: ""
    datalog: ""
    heartbeats: false
    publish_holdings_on_connect: false
  databases:
  - enabled: false
    url: "postgres://lxp:lxp@localhost/lxp"
  mqtt:
  - enabled: true
    host: "localhost"
    port: 1883
    username: ""
    password: ""
    namespace: lxp
  influx:
    enabled: false
    url: "http://localhost:8086"
    username: ""
    password: ""
    database: "lxp"
schema:
  inverters:
  - enabled: bool
    host: str
    port: port
    serial: str
    datalog: str
    heartbeats: bool
    publish_holdings_on_connect: bool
  databases:
  - enabled: bool
    url: url
  mqtt:
  - enabled: bool
    host: str
    port: port
    username: str
    password: password
    namespace: str
  influx:
    enabled: bool
    url: url
    username: str
    password: password
    database: str
